config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper do
    controllers applications: "oauth/applications"
  end

  root "home#index"

  get "documentation", to: "home#documentation", as: "documentation"

  namespace :api, defaults: { format: "json" } do
    scope module: :v1,
          constraints: ApiConstraints.new(version: 1, default: true) do
      resources :lists, path: "bucketlists", except: [:edit, :new] do
        resources :items, except: [:edit, :new], param: :item_id
      end
    end
    match "*url", to: "api#endpoint_not_found", via: :all
  end

  scope path: "users", controller: "users" do
    get "register", to: "users#new", as: "register"
    post "signup", to: "users#create"
  end

  scope path: "auth", controller: "sessions" do
    post "login", to: "sessions#create", as: "login"
    delete "logout", to: "sessions#destroy", as: "logout"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def documentation
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def link_by_signed_in
    if signed_in?
      "/documentation"
    else
      "/"
    end
  end
end

app/views/home/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top bg-navy-blue" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<%= link_by_signed_in %>">Buck<span class="theme-blue">it</span></a>
        </div>

        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                <% unless signed_in? %>
                    <li>
                        <%= link_to 'Home', root_path, class: 'page-link', id: "home-link" %>
                    </li>
                <% end %>
                <li>
                    <%= link_to 'Documentation', documentation_path, class: 'page-link' %>
                </li>
                <% if signed_in? %>
                    <li>
                        <%= link_to 'Your Applications', oauth_applications_path, class: 'page-link' %>
                    </li>
                    <li>
                        <%= link_to 'Log Out', logout_path, class: 'page-link', method: :delete %>
                    </li>
                <% end %>
                <% unless signed_in? %>
                    <li>
                        <%= link_to 'Log In | Sign Up', register_path, class: 'page-link' %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/home/_scroll.js.erb
<script type="text/javascript">
  (function ($) {
    <% if flash %>
      $(function(){
        <% flash.each do |key, value| %>
          $.notify('<%= value %>', '<%= key %>');
        <% end %>
      });
    <% end %>

    $('.page').horizon();

    //Add active class to links on current URL
    var path = window.location.pathname;
    $(".nav .page-link").each(function(){
      if($(this).attr("href") == path || $(this).attr("href") == '' )
      $(this).parents('li').addClass("active");
    });

    var ScrollToggle = function (top, callbackShow, callbackHide) {
      this.ontop = 0;
      this.hontop = 0;
      this.top = top - 20;
      this.show = callbackShow;
      this.hide = callbackHide;
      var self = this;

      (function () {
        $(window).scroll(function (event) {
          var y = getScrollTop();

          if (y >= self.top)
            self.ontop = 1;
          else
            self.ontop = 0;

          if (self.ontop !== self.hontop) {
            if (self.ontop) {
              self.show();
            }
            else {
              self.hide();
            }
          }
          self.hontop = (self.ontop * 1);
        });
      })();
    };

    $('.vertical-slider').unslider({
      autoplay: false,
    });

    var height = $(window).height();
    $('.code-block').each(function(index) {
      new ScrollToggle($(this).position().top + 150, function () {
        if (window.matchMedia('(max-width: 768px)').matches) {
          $('.code-btn').show();
        }
        $('[data-slide="' + index + '"]').trigger('click');
      }, function () {
        $('[data-slide="' + (index - 1) + '"]').trigger('click');
      });
    });

    $(document).on('click', '.code-btn', function() {
      $('.info').toggleClass('no-display');
    });

    function getScrollTop() {
      if (typeof pageYOffset != 'undefined') {
        return pageYOffset;
      }
      else {
        var docBody = document.body;
        var docTypeBody = document.documentElement;
        docTypeBody = (docTypeBody.clientHeight) ? docTypeBody : docBody;
        return docTypeBody.scrollTop;
      }
    };
  })
  (jQuery);

</script>

app/views/home/_sidenav.html.erb
<nav id="affix-nav" class="sidebar col-md-2 col-sm-2 hidden-xs">
    <ul class="nav sidenav" data-spy="affix" data-offset-top="50">
        <li class="active"><a href="#introduction">Introduction</a>
        </li>
        <li><a href="#authentication">Authentication</a>
            <ul class="nav">   
                <li><a href="#signing-up">Signing up</a></li>
                <li><a href="#logging-in">Logging in</a></li>
            </ul>
        </li>
        <li><a href="#get-your-application-started">Get your App Started</a>
        </li>
        <li><a href="#authorization">Authorization</a>
            <ul class="nav">   
                <li><a href="#using-oauth2">Using Oauth2</a></li>
            </ul>
        </li>
        <li><a href="#endpoints">Endpoints</a>
            <ul class="nav">   
                <li><a href="#create-a-bucketlist">Create a Bucketlist</a></li>
                <li><a href="#get-all-bucketlists">Get All Bucketlists</a></li>
                <li><a href="#get-a-bucketlist">Get a Bucketlist</a></li>
                <li><a href="#update-a-bucketlist">Update a Bucketlist</a></li>
                <li><a href="#delete-a-bucketlist">Delete a Bucketlist</a></li>
                <li><a href="#create-a-bucketlist-item">Create a Bucketlist Item</a></li>
                <li><a href="#get-all-bucketlist-items">Get All Bucketlist Items</a></li>
                <li><a href="#get-a-bucketlist-item">Get a Bucketlist Item</a></li>
                <li><a href="#update-a-bucketlist-item">Update a Bucketlist Item</a></li>
                <li><a href="#delete-a-bucketlist-item">Delete a Bucketlist Item</a></li>
            </ul>
        </li>
    </ul>
</nav>

app/views/home/documentation.html.erb
<button class="btn btn-primary code-btn">View Code</button>
<section id="documentation-section" class="page">
  <%= render partial: "doc_content" %>
</section>

app/views/home/index.html.erb
<section id="intro-section" class="page">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div id="intro-caption">
                    <h1>Buck<span class="theme-blue">it</span></h1>
                    <div class="ripple"></div>
                    <p>What would you love to do before you kick the bucket?<br>
                    Get started with your favourite API for managing your bucketlists.</p>
                </div>
            </div>
        </div>
    </div>
</section>